### ISSUE TITLE
support for lists?

### ISSUE THREAD

**Issue by Gregoor** [TheLudd/react-form-data#1]
Hi there,

thanks for providing this very useful Mixin!

I was wondering if you plan on adding support for lists of inputs. For example I would expect the following

``` html
<input type="text" name="url[]" placeholder="Link 1">
<input type="text" name="url[]" placeholder="Link 2">
```

to output this:

``` javascript
{'url': ['Something', 'somethingelse']}
```

Cheers

**Comment by TheLudd** [comment]
Currently there is only list support for checkboxes. I tend not to use this mixin in forms that are more advanced and would like to keep the code as simple as possible. What is your use case?

**Comment by TheLudd** [comment]
Closing due to no response
