### ISSUE TITLE
formDataDidChange isn't called with formData

### ISSUE THREAD

**Issue by leonderijke** [TheLudd/react-form-data#2]
The README states that `formDataDidChange` is called with the form data object as it is after the change was made, but it is called without arguments. It is called after the change, so `this.formData` is already updated.

Maybe the README should be updated and mention that one can get the new state from `this.formData`?

**Comment by TheLudd** [comment]
Thanks for catching this. Will correct it.

**Comment by TheLudd** [comment]
Solved
