### ISSUE TITLE
Doesn't seem to work with <select name="x"><option value="123">123</option></select>

### ISSUE THREAD

**Issue by bf** [TheLudd/react-form-data#5]
I just tried the plugin, and input / textarea fiels are added to the object, but my select element is missing. Is this a known issue?

**Comment by TheLudd** [comment]
Select boxes should work fine. You can clone this repo and run the demo according to the instructions in the readme file. The demo and tests use an old version of react `0.12.x` and if I upgrade tests begin to fail and the demo doesn't work but the mixin itself has no dependencies on react so I cannot see how this would affect anything.
